name: talenties
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  algolia: 1.1.1
  audio_session: 0.1.21
  auto_size_text: 3.0.0
  badges: 2.0.2
  barcode_widget: 2.0.3
  cached_network_image: 3.4.1
  cached_network_image_platform_interface: 4.1.1
  cached_network_image_web: 1.3.1
  chewie: 1.8.5
  cloud_firestore: 5.4.4
  cloud_firestore_platform_interface: 6.4.3
  cloud_firestore_web: 4.3.2
  cloud_functions: 5.1.3
  cloud_functions_platform_interface: 5.5.37
  cloud_functions_web: 4.10.2
  collection: 1.18.0
  csslib: 0.17.3
  dropdown_button2: 2.3.9
  easy_debounce: 2.0.1
  equatable: 2.0.5
  file_picker: 8.1.2
  firebase_auth: 5.3.1
  firebase_auth_platform_interface: 7.4.7
  firebase_auth_web: 5.13.2
  firebase_core: 3.6.0
  firebase_core_platform_interface: 5.3.0
  firebase_core_web: 2.18.1
  firebase_performance: 0.10.0+8
  firebase_performance_platform_interface: 0.1.4+44
  firebase_performance_web: 0.1.7+2
  firebase_storage: 12.3.2
  firebase_storage_platform_interface: 5.1.31
  firebase_storage_web: 3.10.2
  flutter_animate: 4.5.0
  flutter_barcode_scanner: 
    git:
      url: https://github.com/FlutterFlow/flutter_barcode_scanner
      ref: v2.0.0
  flutter_blurhash: 0.8.2
  flutter_cache_manager: 3.4.1
  flutter_google_places: 
    git:
      url: https://github.com/ShehanYjoz/flutter_google_places.git
  flutter_plugin_android_lifecycle: 2.0.20
  flutter_rating_bar: 4.0.1
  flutter_slidable: 3.0.1
  flutter_spinkit: 5.2.0
  flutter_stripe: 11.1.0
  flutter_stripe_web: 6.1.0
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  google_maps: 8.0.0
  google_maps_flutter: 2.9.0
  google_maps_flutter_android: 2.14.7
  google_maps_flutter_ios: 2.13.0
  google_maps_flutter_platform_interface: 2.9.2
  google_maps_flutter_web: 0.5.10
  google_sign_in: 6.2.1
  google_sign_in_android: 6.1.30
  google_sign_in_ios: 5.7.7
  google_sign_in_platform_interface: 2.4.5
  google_sign_in_web: 0.12.4+2
  html: 0.15.4
  image_picker: 1.1.2
  image_picker_android: 0.8.12+13
  image_picker_for_web: 3.0.5
  image_picker_ios: 0.8.12
  image_picker_linux: 0.2.1+1
  image_picker_macos: 0.2.1+1
  image_picker_platform_interface: 2.10.0
  image_picker_windows: 0.2.1+1
  intl: 0.19.0
  json_path: 0.7.2
  just_audio: 0.9.40
  just_audio_platform_interface: 4.3.0
  just_audio_web: 0.4.12
  mapbox_search: 4.2.2
  mime_type: 1.0.0
  octo_image: 2.1.0
  package_info_plus: 8.0.2
  package_info_plus_platform_interface: 3.0.1
  page_transition: 2.1.0
  path_provider: 2.1.4
  path_provider_android: 2.2.10
  path_provider_foundation: 2.4.0
  path_provider_linux: 2.2.1
  path_provider_platform_interface: 2.1.2
  path_provider_windows: 2.3.0
  pin_code_fields: 8.0.1
  plugin_platform_interface: 2.1.8
  provider: 6.1.2
  rxdart: 0.27.7
  share_plus: 10.0.2
  share_plus_platform_interface: 5.0.0
  shared_preferences: 2.3.2
  shared_preferences_android: 2.3.2
  shared_preferences_foundation: 2.5.2
  shared_preferences_linux: 2.4.1
  shared_preferences_platform_interface: 2.4.1
  shared_preferences_web: 2.4.2
  shared_preferences_windows: 2.4.1
  sign_in_with_apple: 6.1.2
  sign_in_with_apple_platform_interface: 1.1.0
  sign_in_with_apple_web: 2.1.0
  simple_gradient_text: 1.2.3
  smooth_page_indicator: 1.1.0
  sqflite: 2.3.3+1
  sqflite_common: 2.5.4+3
  stream_transform: 2.1.0
  stripe_android: 11.1.0
  stripe_ios: 11.1.0
  stripe_js: 6.1.0
  stripe_platform_interface: 11.1.1
  text_search: 1.0.1
  timeago: 3.6.1
  universal_io: 2.2.2
  url_launcher: 6.3.0
  url_launcher_android: 6.3.10
  url_launcher_ios: 6.3.1
  url_launcher_linux: 3.2.0
  url_launcher_macos: 3.2.1
  url_launcher_platform_interface: 2.3.2
  url_launcher_web: 2.3.3
  url_launcher_windows: 3.1.2
  video_player: 2.9.2
  video_player_android: 2.7.13
  video_player_avfoundation: 2.6.2
  video_player_platform_interface: 6.2.3
  video_player_web: 2.3.2
  videosdk: ^1.2.1
  responsive_framework: 1.1.1
  flutter_svg: ^2.0.2
  lottie: ^2.2.0
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  date_time_format: ^2.0.1
  touch_ripple_effect: ^2.2.3


  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.2
  package_info_plus: 8.0.2
  package_info_plus_platform_interface: 3.0.1
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  image: 4.2.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.PNG'
  adaptive_icon_background: '#00000000'
  adaptive_icon_foreground: 'assets/images/adaptive_foreground_icon.PNG'


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
    - assets/svgs/
    - .env

